### ISSUE TITLE
result document missing

### ISSUE THREAD

**Issue by yhxdexy738** [netneurolab/hansen_many_networks#1]
Hello, I am very grateful for the code and resources you provided! They have been very helpful in my learning. 
When I tried to run code"01_show_networks", I found that the "connected vs not connected" part requires the "sc_betzelnull_Schaefer400.npy" file, but this file isn't included in the result folder. I would be very grateful if you share this file.

**Comment by justinehansen** [comment]
The betzell null file is too large to be stored on GitHub but the [line of code](https://github.com/netneurolab/hansen_many_networks/blob/master/code/01_show_networks.py#L348) right before I load in the file shows you how I generate the nulls. This is a python translation from Rick Betzel's original Matlab code (see [here](https://www.brainnetworkslab.com/coderesources) and [this paper](https://www.pnas.org/doi/abs/10.1073/pnas.1720186115)). Hope that helps!

**Comment by yhxdexy738** [comment]
Thanks! That helped a lot
